name: stockdash
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - altair=5.5.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h179d6b4_5
  - aws-c-cal=0.9.8=ha82e055_0
  - aws-c-common=0.12.5=hfd05255_1
  - aws-c-compression=0.3.1=h83e01e5_8
  - aws-c-event-stream=0.5.6=hd31a2bc_4
  - aws-c-http=0.10.7=h4b68edd_1
  - aws-c-io=0.23.2=h460b297_2
  - aws-c-mqtt=0.13.3=hfde8714_8
  - aws-c-s3=0.8.6=haf2eb35_7
  - aws-c-sdkutils=0.2.4=h83e01e5_3
  - aws-checksums=0.2.7=h83e01e5_4
  - aws-crt-cpp=0.35.0=hd7c148e_2
  - aws-sdk-cpp=1.11.606=h2b076a5_6
  - beautifulsoup4=4.14.2=pyha770c72_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.2.0=py311h69b5583_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.11.12=h4c7d964_0
  - cachetools=6.2.2=pyhd8ed1ab_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311h3485c13_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh7428d3b_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - expat=2.7.3=h9214b88_0
  - frozendict=2.4.7=py311h3485c13_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - html5lib=1.1=pyhd8ed1ab_2
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=21.0.0=h0832232_11_cpu
  - libarrow-acero=21.0.0=h7d8d6a5_11_cpu
  - libarrow-compute=21.0.0=h2db994a_11_cpu
  - libarrow-dataset=21.0.0=h7d8d6a5_11_cpu
  - libarrow-substrait=21.0.0=hf865cc0_11_cpu
  - libblas=3.9.0=38_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.9.0=38_h2a3cdd5_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.17.0=h43ecb02_0
  - libdeflate=1.22=h2466b09_0
  - libevent=2.1.12=h3671451_1
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libgomp=15.2.0=h1383e82_7
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=38_hf9ab0e9_mkl
  - libparquet=21.0.0=h7051d1f_11_cpu
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_2
  - libre2-11=2025.11.05=h0eb2380_0
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.0=hfc51747_1
  - libutf8proc=2.11.0=h0b34c2f_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.5=h4fa8253_2
  - lxml=6.0.2=py311hea5fcc3_0
  - lz4-c=1.10.0=h2466b09_1
  - markupsafe=3.0.3=py311h3f79411_0
  - mkl=2025.3.0=hac47afa_454
  - multitasking=0.0.12=pyhd8ed1ab_0
  - narwhals=2.11.0=pyhcf101f3_0
  - numpy=2.3.4=py311h80b3fa1_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.0=h725018a_0
  - orc=2.2.1=h7414dfc_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h11fd7f3_1
  - peewee=3.18.3=py311h9c13b91_0
  - pillow=11.3.0=py311h26a3c52_3
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.4.0=pyhd8ed1ab_0
  - protobuf=6.31.1=py311heca59f8_2
  - pthread-stubs=0.4=h0e40799_1002
  - pyarrow=21.0.0=py311h1ea47a8_1
  - pyarrow-core=21.0.0=py311ha836b3b_1_cpu
  - pycparser=2.22=pyh29332c3_1
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311h3f79411_0
  - re2=2025.11.05=ha104f34_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rpds-py=0.28.0=py311hf51aa87_2
  - scikit-learn=1.7.2=py311h8a15ebc_0
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h7fa0ca8_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlite=3.51.0=hda9a48d_0
  - streamlit=1.51.0=pyhd8ed1ab_1
  - tbb=2022.3.0=hd094cb3_1
  - tenacity=9.1.2=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhd8ed1ab_2
  - tornado=6.5.2=py311h3485c13_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=6.0.0=py311h1ea47a8_2
  - webencodings=0.5.1=pyhd8ed1ab_3
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h6a83c73_3
  - yfinance=0.2.57=pyhd8ed1ab_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.25.0=py311hf893f09_1
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - scipy==1.16.3
prefix: C:\Users\laksh\anaconda3\envs\stockdash
